name = "Foehn"
license = "MIT"
licenselink = "https://github.com/kllmanu/hugo-theme-foehn/blob/master/LICENSE"
description = "A modern, minimalist Hugo theme powered by Tailwind CSS"
homepage = "https://github.com/kllmanu/hugo-theme-foehn"
demosite = "https://foehn.netlify.app"
tags = ["blog", "tailwind"]
features = ["blog", "tailwind"]
min_version = "0.148.2"

[author]
    name = "kllmanu"
    homepage = "https://151190.xyz"